// URLs vazias geram um aviso acessível, nunca um link fictício.
export const profile = {name:'Luis Felipe Vieira', photo:'./perfil.png', linkedin:'https://www.linkedin.com/in/luis-felipe-vieira-79823b22a', github:'https://github.com/devluisfelipevieira', resume:'./curriculo-luis-felipe.pdf', email:'luisvieira.contatoti@gmail.com', phone:'+5524992204099', phoneLabel:'(24) 99220-4099', overview:'./supriti.html'};
export const cases = [
 {id:'supriti',number:'01',title:'SupriTI',category:'Solução interna',summary:'Da necessidade identificada à solução em produção.',status:'Finalizado · Em produção',tags:['Requisitos','Validação','Implantação'],context:'A distribuição de toners era registrada em papel, e os demais insumos não tinham rastreabilidade completa. Era necessário acompanhar o que foi solicitado, aprovado e entregue, por quem e para qual setor.',solution:'Portal interno que reúne catálogo, solicitação, análise técnica, estoque, entrega, confirmação e relatórios. A aprovação reserva os itens; a entrega realiza a baixa física. Ajustes e retificações preservam justificativas e histórico.',role:'Identificação da demanda, levantamento e refinamento de requisitos, definição de regras de negócio e decisões funcionais. Condução do desenvolvimento assistido por IA, testes incrementais, validação e implantação.',tech:'React e Next.js, TypeScript, API NestJS em monólito modular, Prisma e PostgreSQL. Operação com Docker Compose e Traefik com HTTPS. Desenvolvimento assistido por IA; permissões e consistência de estoque verificadas pela API.',result:'Sistema finalizado e em produção, conectando o ciclo de solicitação à confirmação de entrega. Histórico e consumo por setor fornecem uma base para a gestão dos insumos. Ganhos de tempo e indicadores quantitativos ainda serão medidos.'},
 {id:'rede',number:'03',title:'Infraestrutura de rede',category:'Redes & conectividade',summary:'Uma base estruturada para as necessidades do ambiente corporativo.',tags:['Rede corporativa','Conectividade'],context:'Necessidade de uma infraestrutura capaz de atender às demandas básicas e reais de um ambiente corporativo.',solution:'Criação e reconstrução da infraestrutura de rede a partir das necessidades do ambiente.',role:'Identificação das necessidades e atuação na estruturação e implementação da infraestrutura.',tech:'Infraestrutura de rede corporativa. Equipamentos e tecnologias específicos deste case: a confirmar.',result:'Infraestrutura estabelecida para atender às necessidades básicas do ambiente. Detalhes operacionais e informações internas são preservados.'},
 {id:'dominio',number:'04',title:'UCS/AD + Samba',category:'Identidade & arquivos · SEDUC',summary:'Organização de identidades, acessos e serviços de arquivos.',tags:['UCS / AD','Samba','DNS'],context:'Necessidade de organizar domínio, serviços de arquivos e permissões no ambiente de TI.',solution:'Estruturação de serviços de domínio e DNS, grupos, permissões e integração com serviços de arquivos.',role:'Atuação na estruturação e integração dos serviços. Escopo detalhado das atividades: a validar na revisão do case.',tech:'UCS / Active Directory, Samba e DNS. Descrição abstrata, sem endereços, nomes internos ou regras de acesso.',result:'Case de organização de identidades e arquivos. Estado atual e resultados específicos: a confirmar.'},
 {id:'guiche',number:'02',title:'Guichê-PMPS',category:'Solução interna',summary:'Minha primeira solução interna: disponibilidade dos guichês em uma visão compartilhada.',status:'Case de solução implantada',tags:['Atendimento','Tempo real','Implantação'],context:'Necessidade de acompanhar quais guichês estavam livres ou ocupados para apoiar a recepção no encaminhamento do atendimento.',solution:'Sistema com painel de recepção organizado por setor, tela de mesa para atualização de disponibilidade e administração de mesas, perfis e lembretes. As mudanças de status são compartilhadas em tempo real.',role:'Identificação da demanda, levantamento e refinamento de requisitos, regras de negócio e decisões funcionais. Condução do desenvolvimento assistido por IA, testes incrementais, validação e implantação. Foi meu primeiro projeto desenvolvido como solução interna, anterior ao SupriTI.',tech:'React, Vite e TypeScript no frontend; Node.js e Express na API; WebSocket para atualização em tempo real; PostgreSQL e Drizzle ORM. Implantação com Docker Compose e Nginx.',result:'Solução desenvolvida, implantada e utilizada internamente para acompanhar a disponibilidade das mesas. O case registra a experiência de transformar uma demanda operacional em uma ferramenta de apoio ao atendimento.'}
];
export const knowledge = [
 {title:'Sistemas & identidade',items:['Linux','Windows Server','Active Directory / UCS','Samba']},
 {title:'Redes & segurança',items:['MikroTik','OPNsense / pfSense','VLAN','VPN / WireGuard','DNS']},
 {title:'Virtualização',items:['Proxmox','Virtualização']}
];
export const toValidate = ['Docker','DHCP / Kea','Unbound','Suricata','Traefik / Nginx','PostgreSQL','Git'];
