import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {profile,cases,knowledge,toValidate} from './content';
import './style.css';
import {BorderLight} from './BorderLight';
function Brand(){return <img className="brand" src="./logo-lfv-02.svg" alt="LFV" width="32" height="40"/>}
function App(){
 const [menu,setMenu]=useState(false);const [notice,setNotice]=useState('');
 function Link({label,url,primary=false}:{label:string,url:string,primary?:boolean}){return url?<a className={primary?'button primary':'text-link'} href={url} target={/^https?:/.test(url)?"_blank":undefined} rel={/^https?:/.test(url)?"noreferrer":undefined}>{label} <span aria-hidden="true">↗</span></a>:<button className={primary?'button primary':'text-link'} onClick={()=>setNotice(`${label}: link ainda não definido nesta prévia.`)}>{label} <span aria-hidden="true">↗</span></button>}
 return <><a className="skip" href="#conteudo">Pular para o conteúdo</a><header><div className="header-inner"><a href="#inicio" aria-label="Luis Felipe Vieira — início"><Brand/></a><nav aria-label="Navegação principal" className={menu?'open':''}><a href="#sobre" onClick={()=>setMenu(false)}>Sobre</a><a href="#cases" onClick={()=>setMenu(false)}>Cases</a><a href="#conhecimentos" onClick={()=>setMenu(false)}>Conhecimentos</a><a href="#trajetoria" onClick={()=>setMenu(false)}>Trajetória</a><a href="#contato" onClick={()=>setMenu(false)}>Contato</a><div className="mobile-links"><Link label="LinkedIn" url={profile.linkedin}/><Link label="GitHub" url={profile.github}/><Link label="Currículo" url={profile.resume}/></div></nav><div className="header-links"><Link label="LinkedIn" url={profile.linkedin}/><Link label="GitHub" url={profile.github}/><Link label="Currículo" url={profile.resume}/></div><button className="menu-toggle" aria-expanded={menu} aria-label={menu?'Fechar menu':'Abrir menu'} onClick={()=>setMenu(!menu)}>{menu?'Fechar':'Menu'} <span aria-hidden="true">☰</span></button></div></header>
 <main id="conteudo"><section className="hero wrap" id="inicio"><div className="hero-copy"><p className="eyebrow">LUIS FELIPE VIEIRA <span> / </span> PORTFÓLIO PROFISSIONAL</p><h1>Analista de<br/>Infraestrutura <em>de TI.</em></h1><p className="hero-description">Compreender necessidades.<br/>Estruturar soluções.<br/><strong>Acompanhar a implementação.</strong></p><p className="intro">Redes, serviços e soluções internas construídos a partir de problemas reais.</p><div className="actions"><a className="button primary" href="#cases">Conheça os cases <span aria-hidden="true">↓</span></a><a className="button secondary" href="#sobre">Sobre minha atuação</a></div></div><aside className="hero-aside"><div className="portrait-frame"><img src={profile.photo} alt="Retrato profissional de Luis Felipe Vieira" width="1254" height="1254"/></div><div className="portrait-caption"><span>Luis Felipe Vieira</span><small>Infraestrutura & soluções de TI</small></div><div className="aside-note"><span className="line"></span><p>Do entendimento do problema<br/>à aplicação na rotina.</p></div></aside></section>
 <div className="focus-strip"><div className="wrap"><span>INFRAESTRUTURA</span><span>REDES & SERVIÇOS</span><span>RESOLUÇÃO DE PROBLEMAS</span></div></div>
 <section id="sobre" className="wrap about section"><div><p className="eyebrow">01 / SOBRE</p><h2>Tecnologia com<br/>um propósito claro.</h2></div><div className="about-copy"><p>Meu ponto de partida é entender o que precisa funcionar melhor. A partir daí, busco organizar as necessidades, estruturar uma solução e acompanhar sua implementação.</p><p>Minha atuação reúne infraestrutura de TI e iniciativas internas que surgem da observação da rotina. Nos projetos com desenvolvimento assistido por IA, meu papel envolve requisitos, decisões funcionais, testes, validação e implantação.</p></div></section>
 <section id="cases" className="wrap section"><div className="section-heading"><div><p className="eyebrow">02 / CASES</p><h2>Problemas reais.<br/>Soluções em contexto.</h2></div><p>O contexto, as escolhas e minha participação<br className="desktop"/> em cada trabalho.</p></div><div className="cases">{cases.map((item,index)=><article className={`case ${index===0?'featured':''}`} key={item.id} id={item.id}>{index===0&&<BorderLight/>}<div className="case-top"><span className="case-number">{item.number} / {item.category}</span>{item.status&&<span className="status">{item.status}</span>}</div><div className="case-main"><div><h3>{item.title}</h3><p className="case-summary">{item.summary}</p><div className="tags">{item.tags.map(tag=><span key={tag}>{tag}</span>)}</div></div>{index===0&&<div className="project-path"><span>Entender</span><span>Estruturar</span><span>Validar</span><strong>Implantar</strong></div>}</div>{index===0&&<div className="case-overview-action"><a className="overview-strip" href={profile.overview} target="_blank" rel="noreferrer"><span><strong>Conheça o SupriTI por completo</strong><small>Visão geral, telas e decisões do projeto</small></span><span className="overview-arrow" aria-hidden="true">↗</span></a></div>}<details><summary>Explorar case <span aria-hidden="true">+</span></summary><div className="case-details">{[['Contexto',item.context],['Solução',item.solution],['Minha atuação',item.role],['Tecnologias / arquitetura',item.tech],['Resultado',item.result]].map(([title,text])=><div key={title}><h4>{title}</h4><p>{text}</p></div>)}</div></details></article>)}</div></section>
 <section id="conhecimentos" className="knowledge-section"><div className="wrap section"><div className="section-heading"><div><p className="eyebrow">03 / CONHECIMENTOS</p><h2>Uma base técnica<br/>conectada à prática.</h2></div><p>Experiência e contato com tecnologias<br className="desktop"/> apresentados em seus respectivos contextos.</p></div><p className="group-label">EXPERIÊNCIA PRÁTICA EM INFRAESTRUTURA</p><div className="knowledge-grid">{knowledge.map((group,i)=><div key={group.title}><span className="knowledge-number">0{i+1}</span><h3>{group.title}</h3><div className="tags">{group.items.map(x=><span key={x}>{x}</span>)}</div></div>)}</div><div className="project-tech"><div><h3>Tecnologias no contexto de projetos</h3><p>Python, JavaScript, TypeScript e SQL: contato e uso em projetos, sem atribuição de domínio avançado ou autoria integral. Aplicação por projeto a confirmar.</p><div className="tags">{['Python','JavaScript','TypeScript','SQL'].map(x=><span key={x}>{x}</span>)}</div></div><div><h3>Contexto de uso a validar</h3><p>Tecnologias citadas para o portfólio; classificação entre rotina, projeto e estudo pendente nesta prévia.</p><div className="tags">{toValidate.map(x=><span key={x}>{x}</span>)}</div></div></div></div></section>
 <section id="trajetoria" className="wrap section trajectory"><div><p className="eyebrow">04 / EXPERIÊNCIA</p><h2>Atuação em TI.</h2><div className="experience"><span className="small-label">CONTEXTO PROFISSIONAL</span><h3>Infraestrutura e soluções internas</h3><p>Atuação em ambiente de administração pública, com estruturação de rede, serviços de TI e projetos originados de necessidades identificadas na rotina.</p><p className="pending">A confirmar: cargo formal, vínculo e período de atuação.</p><Link label="Histórico completo no currículo" url={profile.resume}/></div></div><div><p className="eyebrow">05 / FORMAÇÃO</p><h2>Formação acadêmica.</h2><div className="education"><article><span className="degree-status">Concluído</span><h3>Análise e Desenvolvimento de Sistemas</h3><p>Tecnólogo · Estácio de Sá</p></article><article><span className="degree-status">Concluída</span><h3>Estrutura e Gestão de Redes de Computadores</h3><p>Pós-graduação · UNINTER</p></article><article><span className="degree-status ongoing">Em andamento</span><h3>Segurança e Defesa Cibernética</h3><p>Pós-graduação · Instituição a confirmar</p></article></div></div></section>
 <section id="contato" className="contact wrap"><div><p className="eyebrow">06 / CONTATO</p><h2>Vamos conversar<br/>sobre o próximo desafio?</h2></div><div><p>Infraestrutura, necessidades reais<br/>e soluções que fazem sentido.</p><div className="actions"><Link label="LinkedIn" url={profile.linkedin} primary/><Link label="E-mail" url={profile.email?`mailto:${profile.email}`:''}/></div><div className="contact-details"><a href={`mailto:${profile.email}`}><span>E-mail</span>{profile.email}</a><a href={`tel:${profile.phone}`}><span>Telefone</span>{profile.phoneLabel}</a></div></div></section></main><footer className="wrap"><a href="#inicio" aria-label="Voltar ao início"><Brand/></a><span>Luis Felipe Vieira <small>Infraestrutura de TI</small></span><p>Prévia 01 · Conteúdo em revisão</p><a href="#inicio">Voltar ao topo ↑</a></footer>{notice&&<div className="notice" role="status"><span>{notice}</span><button onClick={()=>setNotice('')} aria-label="Fechar aviso">×</button></div>}</>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
